version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  caddy: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /gunicorn.sh

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file:
      - ./.envs/.production/.postgres

  caddy:
    build: ./compose/caddy
    depends_on:
      - django
    volumes:
      - caddy:/root/.caddy
    env_file:
      - ./.envs/.production/.caddy
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:3.0
{% if cookiecutter.use_celery == 'y' %}
  celeryworker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
     - postgres
     - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: celery -A {{cookiecutter.project_slug}}.taskapp worker -l INFO

  celerybeat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: celery -A {{cookiecutter.project_slug}}.taskapp beat -l INFO
{% endif %}
